version: '3'

services:
  django_app:
    build: ./django_app
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    networks:
      - unredacted-net

  atlas:
    build: ./atlas
    volumes:
      - ./atlas:/app
    ports:
      - "5000:5000"
    env_file:
      - ./atlas/.env
    networks:
      - unredacted-net

networks:
  unredacted-net:
    driver: bridge
